//
// Created by tomly on 13/09/2026.
//

#ifndef TAP_TEMPO_BOARD_DEFINITION_H
#define TAP_TEMPO_BOARD_DEFINITION_H

#define TICK_FREQUENCY_HZ (1000)

#define LED_GPIO_PORT (GPIO_PORT_B)
#define LED_PIN_RED (GPIO_PIN_13)
#define LED_PIN_GREEN (GPIO_PIN_14)

#define BUTTON_GPIO_PORT (GPIO_PORT_C)
#define BUTTON_PIN (GPIO_PIN_10)

#endif // TAP_TEMPO_BOARD_DEFINITION_H
